[package]
name = "kilo-rs"
version = "0.1.0"
authors = ["Victor Joos <victorjoosdtb@gmail.com>"]

[dependencies]
termion = "*"
regex = "1.0.0"
lazy_static = "1.0.1"
toml = "0.4"
serde="1.0" 
serde_derive="1.0"
